use core::fmt::Display;

/// BACnet object types
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum ObjectType {
    AnalogInput,
    AnalogOutput,
    AnalogValue,
    BinaryInput,
    BinaryOutput,
    BinaryValue,
    Calendar,
    Command,
    Device,
    EventEnrollment,
    File,
    Group,
    Loop,
    MultiStateInput,
    MultiStateOutput,
    NotificationClass,
    Program,
    Schedule,
    Averaging,
    MultiStateValue,
    TrendLog,
    LifeSafetyPoint,
    LifeSafetyZone,
    Accumulator,
    PulseConverter,
    EventLog,
    GlobalGroup,
    TrendLogMultiple,
    LoadControl,
    StructuredView,
    AccessDoor,
    Timer,
    AccessCredential,
    AccessPoint,
    AccessRights,
    AccessUser,
    AccessZone,
    CredentialDataInput,
    BitstringValue,
    CharacterstringValue,
    DatepatternValue,
    DateValue,
    DatetimepatternValue,
    DatetimeValue,
    IntegerValue,
    LargeAnalogValue,
    OctetstringValue,
    PositiveIntegerValue,
    TimepatternValue,
    TimeValue,
    NotificationForwarder,
    AlertEnrollment,
    Channel,
    LightingOutput,
    BinaryLightingOutput,
    NetworkPort,
    ElevatorGroup,
    Escalator,
    Lift,
    Staging,
    AuditLog,
    AuditReporter,
    Color,
    ColorTemperature,
    // Vendor specific range starts at 128
    Custom(u16),
}

impl From<ObjectType> for u16 {
    fn from(obj_type: ObjectType) -> Self {
        match obj_type {
            ObjectType::AnalogInput => 0,
            ObjectType::AnalogOutput => 1,
            ObjectType::AnalogValue => 2,
            ObjectType::BinaryInput => 3,
            ObjectType::BinaryOutput => 4,
            ObjectType::BinaryValue => 5,
            ObjectType::Calendar => 6,
            ObjectType::Command => 7,
            ObjectType::Device => 8,
            ObjectType::EventEnrollment => 9,
            ObjectType::File => 10,
            ObjectType::Group => 11,
            ObjectType::Loop => 12,
            ObjectType::MultiStateInput => 13,
            ObjectType::MultiStateOutput => 14,
            ObjectType::NotificationClass => 15,
            ObjectType::Program => 16,
            ObjectType::Schedule => 17,
            ObjectType::Averaging => 18,
            ObjectType::MultiStateValue => 19,
            ObjectType::TrendLog => 20,
            ObjectType::LifeSafetyPoint => 21,
            ObjectType::LifeSafetyZone => 22,
            ObjectType::Accumulator => 23,
            ObjectType::PulseConverter => 24,
            ObjectType::EventLog => 25,
            ObjectType::GlobalGroup => 26,
            ObjectType::TrendLogMultiple => 27,
            ObjectType::LoadControl => 28,
            ObjectType::StructuredView => 29,
            ObjectType::AccessDoor => 30,
            ObjectType::Timer => 31,
            ObjectType::AccessCredential => 32,
            ObjectType::AccessPoint => 33,
            ObjectType::AccessRights => 34,
            ObjectType::AccessUser => 35,
            ObjectType::AccessZone => 36,
            ObjectType::CredentialDataInput => 37,
            ObjectType::BitstringValue => 39,
            ObjectType::CharacterstringValue => 40,
            ObjectType::DatepatternValue => 41,
            ObjectType::DateValue => 42,
            ObjectType::DatetimepatternValue => 43,
            ObjectType::DatetimeValue => 44,
            ObjectType::IntegerValue => 45,
            ObjectType::LargeAnalogValue => 46,
            ObjectType::OctetstringValue => 47,
            ObjectType::PositiveIntegerValue => 48,
            ObjectType::TimepatternValue => 49,
            ObjectType::TimeValue => 50,
            ObjectType::NotificationForwarder => 51,
            ObjectType::AlertEnrollment => 52,
            ObjectType::Channel => 53,
            ObjectType::LightingOutput => 54,
            ObjectType::BinaryLightingOutput => 55,
            ObjectType::NetworkPort => 56,
            ObjectType::ElevatorGroup => 57,
            ObjectType::Escalator => 58,
            ObjectType::Lift => 59,
            ObjectType::Staging => 60,
            ObjectType::AuditLog => 61,
            ObjectType::AuditReporter => 62,
            ObjectType::Color => 63,
            ObjectType::ColorTemperature => 64,
            ObjectType::Custom(val) => val,
        }
    }
}

impl From<u16> for ObjectType {
    fn from(value: u16) -> Self {
        match value {
            0 => ObjectType::AnalogInput,
            1 => ObjectType::AnalogOutput,
            2 => ObjectType::AnalogValue,
            3 => ObjectType::BinaryInput,
            4 => ObjectType::BinaryOutput,
            5 => ObjectType::BinaryValue,
            6 => ObjectType::Calendar,
            7 => ObjectType::Command,
            8 => ObjectType::Device,
            9 => ObjectType::EventEnrollment,
            10 => ObjectType::File,
            11 => ObjectType::Group,
            12 => ObjectType::Loop,
            13 => ObjectType::MultiStateInput,
            14 => ObjectType::MultiStateOutput,
            15 => ObjectType::NotificationClass,
            16 => ObjectType::Program,
            17 => ObjectType::Schedule,
            18 => ObjectType::Averaging,
            19 => ObjectType::MultiStateValue,
            20 => ObjectType::TrendLog,
            21 => ObjectType::LifeSafetyPoint,
            22 => ObjectType::LifeSafetyZone,
            23 => ObjectType::Accumulator,
            24 => ObjectType::PulseConverter,
            25 => ObjectType::EventLog,
            26 => ObjectType::GlobalGroup,
            27 => ObjectType::TrendLogMultiple,
            28 => ObjectType::LoadControl,
            29 => ObjectType::StructuredView,
            30 => ObjectType::AccessDoor,
            31 => ObjectType::Timer,
            32 => ObjectType::AccessCredential,
            33 => ObjectType::AccessPoint,
            34 => ObjectType::AccessRights,
            35 => ObjectType::AccessUser,
            36 => ObjectType::AccessZone,
            37 => ObjectType::CredentialDataInput,
            39 => ObjectType::BitstringValue,
            40 => ObjectType::CharacterstringValue,
            41 => ObjectType::DatepatternValue,
            42 => ObjectType::DateValue,
            43 => ObjectType::DatetimepatternValue,
            44 => ObjectType::DatetimeValue,
            45 => ObjectType::IntegerValue,
            46 => ObjectType::LargeAnalogValue,
            47 => ObjectType::OctetstringValue,
            48 => ObjectType::PositiveIntegerValue,
            49 => ObjectType::TimepatternValue,
            50 => ObjectType::TimeValue,
            51 => ObjectType::NotificationForwarder,
            52 => ObjectType::AlertEnrollment,
            53 => ObjectType::Channel,
            54 => ObjectType::LightingOutput,
            55 => ObjectType::BinaryLightingOutput,
            56 => ObjectType::NetworkPort,
            57 => ObjectType::ElevatorGroup,
            58 => ObjectType::Escalator,
            59 => ObjectType::Lift,
            60 => ObjectType::Staging,
            61 => ObjectType::AuditLog,
            62 => ObjectType::AuditReporter,
            63 => ObjectType::Color,
            64 => ObjectType::ColorTemperature,
            _ => ObjectType::Custom(value),
        }
    }
}

impl Display for ObjectType {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            ObjectType::AnalogInput => write!(f, "Analog Input"),
            ObjectType::AnalogOutput => write!(f, "Analog Output"),
            ObjectType::AnalogValue => write!(f, "Analog Value"),
            ObjectType::BinaryInput => write!(f, "Binary Input"),
            ObjectType::BinaryOutput => write!(f, "Binary Output"),
            ObjectType::BinaryValue => write!(f, "Binary Value"),
            ObjectType::Calendar => write!(f, "Calendar"),
            ObjectType::Command => write!(f, "Command"),
            ObjectType::Device => write!(f, "Device"),
            ObjectType::EventEnrollment => write!(f, "Event Enrollment"),
            ObjectType::File => write!(f, "File"),
            ObjectType::Group => write!(f, "Group"),
            ObjectType::Loop => write!(f, "Loop"),
            ObjectType::MultiStateInput => write!(f, "Multi-State Input"),
            ObjectType::MultiStateOutput => write!(f, "Multi-State Output"),
            ObjectType::NotificationClass => write!(f, "Notification Class"),
            ObjectType::Program => write!(f, "Program"),
            ObjectType::Schedule => write!(f, "Schedule"),
            ObjectType::Averaging => write!(f, "Averaging"),
            ObjectType::MultiStateValue => write!(f, "Multi-State Value"),
            ObjectType::TrendLog => write!(f, "Trend Log"),
            ObjectType::LifeSafetyPoint => write!(f, "Life Safety Point"),
            ObjectType::LifeSafetyZone => write!(f, "Life Safety Zone"),
            ObjectType::Accumulator => write!(f, "Accumulator"),
            ObjectType::PulseConverter => write!(f, "Pulse Converter"),
            ObjectType::EventLog => write!(f, "Event Log"),
            ObjectType::GlobalGroup => write!(f, "Global Group"),
            ObjectType::TrendLogMultiple => write!(f, "Trend Log Multiple"),
            ObjectType::LoadControl => write!(f, "Load Control"),
            ObjectType::StructuredView => write!(f, "Structured View"),
            ObjectType::AccessDoor => write!(f, "Access Door"),
            ObjectType::Timer => write!(f, "Timer"),
            ObjectType::AccessCredential => write!(f, "Access Credential"),
            ObjectType::AccessPoint => write!(f, "Access Point"),
            ObjectType::AccessRights => write!(f, "Access Rights"),
            ObjectType::AccessUser => write!(f, "Access User"),
            ObjectType::AccessZone => write!(f, "Access Zone"),
            ObjectType::CredentialDataInput => write!(f, "Credential Data Input"),
            ObjectType::BitstringValue => write!(f, "Bitstring Value"),
            ObjectType::CharacterstringValue => write!(f, "Characterstring Value"),
            ObjectType::DatepatternValue => write!(f, "Datepattern Value"),
            ObjectType::DateValue => write!(f, "Date Value"),
            ObjectType::DatetimepatternValue => write!(f, "Datetimepattern Value"),
            ObjectType::DatetimeValue => write!(f, "Datetime Value"),
            ObjectType::IntegerValue => write!(f, "Integer Value"),
            ObjectType::LargeAnalogValue => write!(f, "Large Analog Value"),
            ObjectType::OctetstringValue => write!(f, "Octetstring Value"),
            ObjectType::PositiveIntegerValue => write!(f, "Positive Integer Value"),
            ObjectType::TimepatternValue => write!(f, "Timepattern Value"),
            ObjectType::TimeValue => write!(f, "Time Value"),
            ObjectType::NotificationForwarder => write!(f, "Notification Forwarder"),
            ObjectType::AlertEnrollment => write!(f, "Alert Enrollment"),
            ObjectType::Channel => write!(f, "Channel"),
            ObjectType::LightingOutput => write!(f, "Lighting Output"),
            ObjectType::BinaryLightingOutput => write!(f, "Binary Lighting Output"),
            ObjectType::NetworkPort => write!(f, "Network Port"),
            ObjectType::ElevatorGroup => write!(f, "Elevator Group"),
            ObjectType::Escalator => write!(f, "Escalator"),
            ObjectType::Lift => write!(f, "Lift"),
            ObjectType::Staging => write!(f, "Staging"),
            ObjectType::AuditLog => write!(f, "Audit Log"),
            ObjectType::AuditReporter => write!(f, "Audit Reporter"),
            ObjectType::Color => write!(f, "Color"),
            ObjectType::ColorTemperature => write!(f, "Color Temperature"),
            ObjectType::Custom(val) => write!(f, "Custom({})", val),
        }
    }
}
